<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INmadhun03" failures="1" tests="5" name="Test" time="0.038" errors="0" timestamp="2022-10-29T12:30:57 IST">
  <testcase classname="com.qa.Mytests.RetryLogic" name="retry1" time="0.006">
    <skipped/>
  </testcase> <!-- retry1 -->
  <testcase classname="com.qa.Mytests.RetryLogic" name="retry1" time="0.001">
    <skipped/>
  </testcase> <!-- retry1 -->
  <testcase classname="com.qa.Mytests.RetryLogic" name="retry1" time="0.001">
    <skipped/>
  </testcase> <!-- retry1 -->
  <testcase classname="com.qa.Mytests.RetryLogic" name="retry1" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.Mytests.RetryLogic.retry1(RetryLogic.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- retry1 -->
  <testcase classname="com.qa.Mytests.RetryLogic" name="retry2" time="0.001"/>
</testsuite> <!-- Test -->
